### PR TITLE
Add documentation for endpoints

### PR DESCRIPTION
**Pull request by seancorc**
## Overview

  
Added documentation for creating, updating, deleting, and getting announcements.

 
  ## Next Steps

  
Adding setup instructions (https://github.com/cuappdev/announcements-backend/issues/5).

### CODE REVIEW

**Review by alanna-zhou — APPROVED** [review]
very cool!

**Review by kq-li — APPROVED** [review]
sick

**Review by meganle — APPROVED** [review]
send it

**Review by manishsaha — APPROVED** [review]
perf

**Pull request merged**
